### ISSUE TITLE
I`m getting connection failed

### ISSUE THREAD

**Issue by yargomascarenhas** [HoN-Revival/Mac-Private-Server-Connect#1]
Using the script
<img width="704" alt="Screen Shot 2022-08-01 at 14 22 06" src="https://user-images.githubusercontent.com/8085584/182206950-3bb7d586-30b1-4333-9876-acec5649a7c5.png">

I still have this:
<img width="495" alt="Screen Shot 2022-08-01 at 14 22 30" src="https://user-images.githubusercontent.com/8085584/182207036-b94557db-550e-4f76-aa4c-2c0249879fce.png">

**Comment by yargomascarenhas** [comment]
This works now, maybe a connection error or server unavailable.

**Comment by mrhappyasthma** [comment]
Yeah, that server has been going on/off.

Now that project kongor is launched, I recommend looking in to `kongor.online` for the server links.
